version: "3"
services:
  app:
    image: "ikt206-flask-example_application"
    build: .
    depends_on:
      -   pgdb
    ports:
      - 8080:80

  pgdb:
    image: postgres
    restart: always
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
