name: build

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
    branch:
      - master

env:
  REGISTRY: ghcr.io

jobs: 

  build:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3

      -
        name: Log in to GHCR
        uses: docker/login-action@v1.12.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Extract metadata for the Docker image
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      -
        name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}


  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run with setup-python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Install  requirements
        run: |
          pip install -r src/requirements.txt
      - name: Run tests
        run: coverage run src/app_test.py
      - name: Test report
        run: coverage report

  deploy:
    needs: test
    runs-on: self-hosted
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy to Docker host
        run: |
          docker stop app || true
          docker rm app || true
          docker run -d -p 5000:5000 --name app ${{ env.REGISTRY }}/${{ github.repository }}:latest
