name: Test run

on:
  push:
    tags-ignore:
      - '*'
    branches:
      - '**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/base

jobs:
  build: 
    runs-on: self-hosted
    steps:
      - 
       name: Docker Setup Buildx
       uses: docker/setup-buildx-action@v1.6.0

      - 
        name: Log in to GHCR
        uses: docker/login-action@v1.12.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - 
        name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3.6.2
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - 
        name: Build and push Docker image
        uses: docker/build-push-action@v2.8.0
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run with setup-python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Install  requirements
        run: |
          pip install -r requirements.txt
      - name: Run tests
        run: coverage run app_test.py
      - name: Test report
        run: coverage report
  
  #  deploy: 
  #    needs: test
  #     environment: prod
  #     runs-on: ubuntu-latest