name: Test run 
on:
  push:
    tags-ignore:
      - '*'
    branches:
      - '**'
jobs:
  build: 
    runs-on: self-hosted
    steps:
      # name: Setup
      #   uses: |
      #     echo POSTGRES_USER=${POSTGRES_USER} > .venv
      #     echo POSTGRES_PASSWORD=${POSTGRES_PASSWORD} >> .venv
      #     echo POSTGRES_DB=${POSTGRES_DB} >> .venv
      
      uses: actions/checkout@v3
      name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          #registry: registry.internal.uia.no/ikt206-g-23v-devops/LabGroup20/exam
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      name: Docker build
      run: |
        docker build
        docker push


  test:
    runs-on: ubuntu-latest
    steps:
      uses: actions/checkout@v3
      name: Run with setup-python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      name: Install  requirements
        run: |
          pip install -r requirements.txt
      name: Run tests
        run: |
          pytest
          coverage run app_test.py
      name: Test report
        run: coverage report
  
  #  deploy: 
  #    needs: test
  #     environment: prod
  #     runs-on: ubuntu-latest