name: Test run

on:
  push:
    tags-ignore:
      - '*'
    branches:
      - '**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/base

jobs:
  build: 
    runs-on: self-hosted
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
       name: Docker Setup Buildx
       uses: docker/setup-buildx-action@v2

      - 
        name: Log in to GHCR
        uses: docker/login-action@v1.12.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Build and push Docker image
          run: |
            docker build . --tag ghcr.io/charlottethorjussen/hello-docker-gcr-demo:latest
            docker run ghcr.io/charlottethorjussen/hello-docker-gcr-demo:latest
            docker push ghcr.io/charlottethorjussen/hello-docker-gcr-demo:latest

        # uses: docker/build-push-action@v4
        # with:
        #   context: .
        #   push: true
        #   tags: user/app:latest
        #   labels: ${{ steps.meta.outputs.labels }}

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run with setup-python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Install  requirements
        run: |
          pip install -r requirements.txt
      - name: Run tests
        run: coverage run app_test.py
      - name: Test report
        run: coverage report
  
  #  deploy: 
  #    needs: test
  #     environment: prod
  #     runs-on: ubuntu-latest